# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [27]:
import pandas as pd

ins_df1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

ins_df2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")

ins_df3 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [29]:
ins_df1.columns = ins_df1.columns.str.lower().str.strip().str.replace(" ", "_")
ins_df1.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [30]:
ins_df2.columns = ins_df2.columns.str.lower().str.strip().str.replace(" ", "_")
ins_df2.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

In [31]:
ins_df3.columns = ins_df3.columns.str.lower().str.strip().str.replace(" ", "_")
ins_df3.head()

,customer,state,customer_lifetime_value,education,gender,income,monthly_premium_auto,number_of_open_complaints,policy_type,total_claim_amount,vehicle_class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [32]:
print(ins_df1.columns)
print(ins_df2.columns)
print(ins_df3.columns)

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')
Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class'],
      dtype='str')
Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='str')

In [35]:
ins_df3 = ins_df3.rename(columns = {"state" : "st"})

ins_df_general = pd.concat([ins_df1, ins_df2, ins_df3], ignore_index = True)

ins_df_general

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
12069,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
12070,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
12071,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
12072,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
12073,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [36]:
ins_df_general.isnull().all(axis=1).sum()

np.int64(2937)

In [37]:
ins_df_general = ins_df_general.dropna(how="all")

In [38]:
ins_df_general.isnull().sum()

customer                       0
st                             0
gender                       122
education                      0
customer_lifetime_value        7
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [39]:
ins_df_general["gender"].value_counts(dropna=False)

gender
F         4560
M         4368
NaN        122
Male        40
female      30
Femal       17
Name: count, dtype: int64

In [40]:
ins_df_general["gender"] = ins_df_general["gender"].replace({
    "female": "F",
    "Femal": "F",
    "Male": "M"
})

In [41]:
ins_df_general["gender"].value_counts(dropna=False)

gender
F      4607
M      4408
NaN     122
Name: count, dtype: int64

In [42]:
ins_df_general["customer_lifetime_value"].dtype

dtype('O')

In [43]:
ins_df_general["customer_lifetime_value"].head(10)

0            NaN
1     697953.59%
2    1288743.17%
3     764586.18%
4     536307.65%
5     825629.78%
6     538089.86%
7     721610.03%
8    2412750.40%
9     738817.81%
Name: customer_lifetime_value, dtype: object

In [44]:
has_percent = ins_df_general["customer_lifetime_value"].astype(str).str.contains("%")

ins_df_general["customer_lifetime_value"] = pd.to_numeric(
    ins_df_general["customer_lifetime_value"]
    .astype(str)
    .str.replace("%", "", regex=False),
    errors="coerce"
)

ins_df_general.loc[has_percent, "customer_lifetime_value"] /= 100

In [45]:
ins_df_general["customer_lifetime_value"].head(10)

0           NaN
1     6979.5359
2    12887.4317
3     7645.8618
4     5363.0765
5     8256.2978
6     5380.8986
7     7216.1003
8    24127.5040
9     7388.1781
Name: customer_lifetime_value, dtype: float64

In [46]:
ins_df_general["customer_lifetime_value"].dtype

dtype('float64')

In [47]:
ins_df_general["number_of_open_complaints"].value_counts(dropna=False)

number_of_open_complaints
0         5629
1/0/00    1626
1          765
2          283
1/1/00     247
3          230
4          119
1/2/00      93
1/3/00      60
5           44
1/4/00      29
1/5/00      12
Name: count, dtype: int64

In [48]:
ins_df_general["number_of_open_complaints"] = ins_df_general["number_of_open_complaints"].replace({
    "1/0/00": 0,
    "1/1/00": 1,
    "1/2/00": 2,
    "1/3/00": 3,
    "1/4/00": 4,
    "1/5/00": 5
})

In [49]:
ins_df_general["number_of_open_complaints"] = ins_df_general["number_of_open_complaints"].astype(int)

In [50]:
ins_df_general["number_of_open_complaints"].value_counts()

number_of_open_complaints
0    7255
1    1012
2     376
3     290
4     148
5      56
Name: count, dtype: int64

In [51]:
ins_df_general["st"].value_counts(dropna=False)

st
California    3032
Oregon        2601
Arizona       1630
Nevada         882
Washington     768
Cali           120
AZ              74
WA              30
Name: count, dtype: int64

In [52]:
ins_df_general["st"] = ins_df_general["st"].replace({
    "Cali": "California",
    "AZ": "Arizona",
    "WA": "Washington"
})

In [53]:
ins_df_general["st"].value_counts()

st
California    3152
Oregon        2601
Arizona       1704
Nevada         882
Washington     798
Name: count, dtype: int64

In [54]:
ins_df_general["education"].value_counts(dropna=False)

education
Bachelor                2719
College                 2682
High School or Below    2616
Master                   752
Doctor                   344
Bachelors                 24
Name: count, dtype: int64

In [55]:
ins_df_general["education"] = ins_df_general["education"].replace({
    "Bachelors": "Bachelor"
})

In [56]:
ins_df_general["education"].value_counts()

education
Bachelor                2743
College                 2682
High School or Below    2616
Master                   752
Doctor                   344
Name: count, dtype: int64

In [57]:
ins_df_general["vehicle_class"].value_counts(dropna=False)

vehicle_class
Four-Door Car    4641
Two-Door Car     1896
SUV              1774
Sports Car        483
Luxury SUV        182
Luxury Car        161
Name: count, dtype: int64

In [58]:
ins_df_general["policy_type"].value_counts(dropna=False)

policy_type
Personal Auto     6792
Corporate Auto    1965
Special Auto       380
Name: count, dtype: int64

In [59]:
ins_df_general.dtypes

customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints      int64
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [60]:
ins_df_general.isnull().sum()

customer                       0
st                             0
gender                       122
education                      0
customer_lifetime_value        7
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [61]:
ins_df_general.duplicated().sum()

np.int64(3)

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [65]:
marketing_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
marketing_df.head(5)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [66]:
marketing_df["sales_channel"].value_counts()

sales_channel
Agent          4121
Branch         3022
Call Center    2141
Web            1626
Name: count, dtype: int64

In [67]:
marketing_df[
    [
        "sales_channel",
        "customer_lifetime_value",
        "monthly_premium_auto",
        "total_claim_amount"
    ]
].head()

,sales_channel,customer_lifetime_value,monthly_premium_auto,total_claim_amount
0,Agent,4809.216960,61,292.800000
1,Call Center,2228.525238,64,744.924331
2,Call Center,14947.917300,100,480.000000
3,Branch,22332.439460,97,484.013411
4,Branch,9025.067525,117,707.925645

In [69]:
revenue_by_channel = marketing_df.pivot_table(
    index="sales_channel",
    values="monthly_premium_auto",
    aggfunc="sum"
)

revenue_by_channel

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

In [71]:
revenue_by_channel = revenue_by_channel.round(2)
revenue_by_channel

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

In [73]:
clv_by_gender_education = marketing_df.pivot_table(
    index="gender",
    columns="education",
    values="customer_lifetime_value",
    aggfunc="mean"
)

clv_by_gender_education

education,Bachelor,College,Doctor,High School or Below,Master
gender,,,,,
F,7874.269478,7748.823325,7328.508916,8675.220201,8157.053154
M,7703.601675,8052.459288,7415.333638,8149.687783,8168.832659

In [74]:
clv_by_gender_education = clv_by_gender_education.round(2)
clv_by_gender_education

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here